### PR TITLE
Mention --assume-ready of datalad-run

### LINKED ISSUE #697: Mention `run --assume-ready`
> `--assume-ready {inputs|outputs|both}` Assume that inputs do not need to be retrieved and/or outputs do not need to unlocked or removed before running the command. This option allows you to avoid the expense of these preparation steps if you know that they are unnecessary.

This is very useful and deserves a mention.

### PR DESCRIPTION
**Pull request by adswa**
This adds a short paragraph in the chapter on datalad run's input and output options,
and adds a bullet point in the summary of datalad run, on the recently introduced
--assume-ready flag that skips the preparation of --inputs and --outputs if a user
has retrieved/unlocked them already
Fixes #697.

ping @mih

### CODE REVIEW

**Comment by adswa** [comment]
Mhh, the unit tests seem to be messed up. Pushing an empty commit to retrigger the build

**Comment by adswa** [comment]
Somehow we lost travis. Investigating...

**Comment by adswa** [comment]
So, we ran out of Travis.com credits. For some reason, I thought they allocated a fixed but recurring amount of credits to open source projects, but its a one-time allocation only. I have now replaced the travis setup with github actions. They provide 2000 build minutes per month for free, which should suffice.

**Comment by adswa** [comment]
ping @mih - is this good to go?

**Comment by adswa** [comment]
oh dang, this branch has the CI setup...

**Review by mih — APPROVED** [review]
Yes, this works. Thx!

**Pull request merged**
