### PR TITLE
Update the DVC section

### PR DESCRIPTION
**Pull request by mslw**
Minor fixes for things I noticed when preparing for a workshop. See commit messages for details.

Lacks run records, which prevents merge, but depends on appveyor succeeding (see below), so I leave this in draft mode. Otherwise quite complete.

Remaining todos and issues (help welcome):

- [x] Update run records. Some of the commits touch the `runrecord` directives and they will require updating the built [run records](https://handbook.datalad.org/en/latest/contributing.html#automatic-builds), preferably with artifacts from AppVeyor once it succeeds (see comment below).
- [x] Remove git errors when pushing tags. Currently, two outputs in the DVC workflow (ctrl-f in [this section](https://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html#id13)) contain "error" and "fatal" messages coming from git. My first impression is that they are caused by being unable to push tags that already exist (but probably are attached to different commit ids). Might be a holdover from some previous run, or a cleaning error? There are some `.. only:: adminmode` directives that create a local push target to serve as origin, after all. (nothing critical by any means)

### CODE REVIEW

**Comment by mslw** [comment]
Appveyor error seems to be https://github.com/datalad/datalad/issues/7286 - looks like I'll be building locally 🙃

**Review by adswa — COMMENTED** [review]
Oh wow, you found quite a bunch of problems! Thanks much for digging through this. I'll see if I can get Appveyor to work again :+1:

**Comment by adswa** [comment]
As for:

>     * [ ]  Remove git errors when pushing tags. Currently, two outputs in the DVC workflow (ctrl-f in [this section](https://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html#id13)) contain "error" and "fatal" messages coming from git. My first impression is that they are caused by being unable to push tags that already exist (but probably are attached to different commit ids). Might be a holdover from some previous run, or a cleaning error? There are some `.. only:: adminmode` directives that create a local push target to serve as origin, after all. (nothing critical by any means)

I believe you are referring to error such as this one, right? 

```
error: src refspec sgd-pipeline matches more than one
error: failed to push some refs to '/home/me/pushes/data-version-control'
```

First of all, thanks for catching them! I believe the problem is that there is both a tag and a branch with the same name (``sgd-pipeline`` and ``random-forest``, and (I think) this is due to the fact that they exist on GitHub... I have removed them upstream, and triggered another appveyor build. Let's see :crossed_fingers:

**Comment by adswa** [comment]
Alright, I have addressed your TODOs @mslw. I'm marking this as ready.

**Review by adswa — APPROVED** [review]

**Pull request merged**
