### PR TITLE
PDF tune-ups

### PR DESCRIPTION
**Pull request by adswa**
I hope that this PR can make the PDF version of the book fully functional. What's missing for this is some sort of border or box around findoutmore directives. This was easy to do for Gitusernotes, but the findoutmores are nasty.

- [x] boxes around findoutmore's
- minor tuning/fixes
   - [ ] Fix links with custom descriptions to html documents as done in 
b60ac7f 
   - [ ] less crappy title page:
        - [x] Logo
        - [x] contributor names of two people are still their GitHub handles
   - [x] add user type section to the appendix - no difference for html, but now its not the very first thing readers of the PDF see

### CODE REVIEW

**Comment by adswa** [comment]
uhhh the commit history here suggests some failures during my rebasing attempts. The file changes are conforming to what I want to merge in here though. I will give the findoutmore delineation another whack and will probably merge this later regardless of the messy commit history in this branch.

**Comment by adswa** [comment]
I am quite satisfied with this. It still has stuff to take care of (e.g., it is hard to find the links that are relative paths to html, and I'm sure that there are many more to find in the future), and some parts a still a bit awkward (e.g., page-long or nested findoutmores suck a lot in anything that is not an html toggle, but thanks to @mih's change they are *identifiable* as findoutmores now. Therefore, for the first time ever, the book has a PDF version that has an unambiguous, *readable* structure :tada:
Screenshot from 2020-05-18 13-37-23

**Comment by mih** [comment]
We should make the notion of something to "click on" go away in the PDF. Needs some thinking... Later... ;-)

**Comment by adswa** [comment]
hihi... true

**Pull request merged**
