### PR TITLE
add instructions to reset AWS keys when downloading HCP data

### LINKED ISSUE #620: Mistyped AWS credentials when downloading HCP data
**Is your feature request related to a problem? Please describe.**
I was following the [datalad handbook instructions](http://handbook.datalad.org/en/latest/usecases/HCP_dataset.html) for downloading the HCP data. However, I accidentally misentered my AWS secret key and failed to download any of the subjects using `datalad get`. I tried to find the `.aws` folder that would contain my AWS keys but then realized that datalad uses the system keychain to save this info.

**Describe the solution you'd like**
I managed to find a way to edit my AWS keys using the `keyring` package in Python. The solution is below. I was wondering whether this solution would be wanted somewhere in the datalad handbook?

```python
import keyring

keyring.set_password("datalad-hcp-s3", "key_id", <password>)
keyring.set_password("datalad-hcp-s3", "secret_id", <password>)
```

### PR DESCRIPTION
**Pull request by josephmje**
Closes #620 

Thank you @adswa for your feedback on my original issue. I've made some changes using the markup you suggested there. Should I also document the other alternatives you mentioned (eg. modifying `keyring_pass.cfg` or setting environment variables)? Or do you think this solution would cover most people's computers?

### CODE REVIEW

**Review by adswa — COMMENTED** [review]
Thanks much @josephmje! Also for finding and fixing all those spelling and syntax errors :) 

> Should I also document the other alternatives you mentioned (eg. modifying keyring_pass.cfg or setting environment variables)? 

It would be fantastic if you could mention that one could set environment variables with their credentials as an alternative, and the names of the corresponding environment variables (``DATALAD_hcp_s3_key_id`` and ``DATALAD_hcp_s3_secret_id``). There is a bit of general information about environment variables in a footnote in the section on configurations, and you can add a reference to it with the following markup:

```RST
see :ref:`this footnote <envvars>` for more details
```
where you can add arbitrary text in place of "this footnote"
 

I've added a diff patch on how to fix the indentation error that Sphinx complains about below.

@all-contributors please add @josephmje for content

**Comment by adswa** [comment]
Good thing the bot didn't seem to listen, I forgot an emoji key.

hey @all-contributors please add @josephmje for content, bug

**Review by adswa — APPROVED** [review]
Great, thanks! I will merge this now. :)

Just to be sure this information wasn't lost in past conversations: Please feel free to add your information to .zenodo.json or just paste it here and I can include it. With the upcoming DataLad 0.14.0 release there will be a new handbook release, and everyone listed in the zenodo.json file becomes a co-author on https://zenodo.org/record/3905791#.X9HYZSUo8UE with every new release.

**Comment by josephmje** [comment]
Thank you @adswa for the review and Sphinx tips! I've added my information here:

```
    {
      "affiliation": "The Centre for Addiction and Mental Health",
      "name": "Joseph, Michael",
      "orcid": "0000-0002-0068-230X"
    }
```

**Comment by adswa** [comment]
Great, thanks - done in #628

**Pull request merged**
