### PR TITLE
Refactor the chapter on publishing

### PR DESCRIPTION
**Pull request by adswa**
[Duplicate of #761 in hopes to trigger a readthedocs preview that was somehow lost on the way]

This work-in-progress PR starts a larger effort on restructuring and extending the handbooks content on publishing datasets to third party services.

In particular, it
- separated service-specific walk-throughs into standalone sections. This affected the "intro" section in particular, from which content on configuring dropbox as a special remote, exporting dataset contents to figshare, and using Git-lfs have each been transformed into standalone sections in the chapter. At the moment, there are walk-throughts for dropbox, s3, figshare, git lfs and gin. This new structure may also make it easier to add new services as walk-throughs.
- improved the introduction into the topic of dataset publication. I have split it into different usecases depending on the capabilities of the employed third party services. The intro lists them, and links to the relevant walk-throughs later in the chapter.
- added a standalone section on data privacy
- extended the example on exporting datasets to figshare with screenshots and code

There is still missing content and room for improvement:

- [x] The placeholder section on publishing datasets to git repository hosting services needs to be filled with the current commands and procedures to do this
- [x] The placeholder section on publishing datasets to git repository hosting services needs to document the new ``create-sibling-{github/gogs/gitlab...}`` command that will come in ``0.16.0``
- [ ] The walkthroughs might benefit from a more generic setup, such as the one that @jsheunis has created in the S3 workflow, where the section is a complete stand-alone piece including the generation of a dataset to publish. If we adopt this approach for the other walk-throughs, too, their content can become more accessible and would not require readers to e.g., have a "DataLad-101" dataset from the previous chapters to publish.
- [x] the section on data privacy could be extended with more strategies and ideas or examples - at the moment, its a lose and hastily collected set of ideas. @mslw maybe has more content based on his work on the RDM module on this topic

### CODE REVIEW

**Comment by adswa** [comment]
@mslw this is far enough for an initial review. Would you be so kind to take a brief look? You should be able to click on the readthedocs CI check for a preview. The last chapter of the basics, Third party publishing, has been completely restructured and rewritten. 

I'd appreciate any kind of feedback, but would be particularly grateful for a brainstorming on more strategies to prevent data leaks (I so far only put down quick ideas)

**Comment by mslw** [comment]
I'm taking a look. Thanks for the heads-up about the preview, I didn't know about that feature. I found the build based on this PR by going to readthedocs and choosing "builds" from the version menu, is there another way?

**Comment by adswa** [comment]
> I'm taking a look. Thanks for the heads-up about the preview, I didn't know about that feature. I found the build based on this PR by going to readthedocs and choosing "builds" from the version menu, is there another way?

Yes, right here in this PR in the list of passed checks - if you click "details" on the check "docs/readthedocs.org:datalad-handbook" it takes you to https://datalad-handbook--762.org.readthedocs.build/en/762/. 

In there it is https://datalad-handbook--762.org.readthedocs.build/en/762/basics/basics-thirdparty.html 

Thank you!

**Comment by mslw** [comment]
I read the chapter, skimming through some sections. Here are a few things which caught my attention, organised by section (so the data leaks are at the end).

### Beyond shared infrastructure
I really like the new structure, with walk-throughs moved into separate sections. This introduction gives a nice overview on publishing, covers what I wanted to know and sets the field for the examples. No complaints here (I found two typos, save -> safe, "remote ," but that's barely worth mentioning).

### Publishing datasets to Git repository hosting
- Fig. 8.4 with an example of manual repository creation shows gin web interface. This made me pause for a little. I guess gin is a fine example (it's a git hosting service after all, and the boxes to fill are pretty much the same everywhere) but it is also a unique case in this context.
- The "Authentication by token" subsection is nice and should stay here (see also comment below). But, IIRC, the token authentication is an alternative to SSH keys (in that the ssh keys are used with ssh and tokens with https). The walkthrough starts with SSH, and discusses `--access-protocol` option later. Maybe worth adding to the first paragraph of this subsection that it will depend on your configuration / choice of options?

### Walk-through: Amazon S3 as a special remote
This section has a note on token authentication, though this time it is different and also suggests adding the token to git config. At first glance this could be described only in one place (end of the section on publishing to git hosting) to improve flow / brevity of other sections. But one could also argue that keeping it in both makes the walk-throughs self-contained. So after I wrote it down I'm not sure which way is better.

### Keeping (some) dataset contents private
To be fair, I don't have many ideas here. My thinking (in the workshop context) was mainly along the line of "`git mv` preserves the rename information, so if you track it, so can others". You already cover that in "Strategy 1: Never save private information to Git" when you write:
> However, it is highly important to realize that while annexed file’s contents are not saved into Git, annex file’s names are. If private information such as a medical patients non-anonymized ID or other potentially identifying information becomes a part of the file name, this information is exposed in the Git history of the dataset.

Maybe we could drive it in further by adding "This stays true even if you rename the files, because rename operations are also maintained in the logs", but I don't think it can be fleshed out much more.

The one new thing that comes to my mind is the peculiarity of compression pointed out by miykael [here](https://neurostars.org/t/attention-with-anonymization-and-gzipped-files-you-might-be-publishing-subject-information/1623) - under some circumstances (`gzip` without the `-n --no-name` option) if you rename a single file compressed by gzip, it will still produce the original name after unpacking. But I'm not sure if it fits well with general theme of this section.

**Comment by adswa** [comment]
> I found two typos, save -> safe, "remote ," but that's barely worth mentioning

It would be great if you can just add a review commit fixing them here in this PR, if its not too much trouble. The handbook is full of typos, and I'd like to get rid of them. Its hard to find them with only vague descriptions :-) 

Thanks for the review! I added your suggestions. @all-contributors please add @mslw for review

**Comment by adswa** [comment]
@all-contributors please add @mslw for review

**Comment by adswa** [comment]
feel free to add yourself to `zenodo.json`, @mslw

**Comment by adswa** [comment]
I'll merge this in. Typically, I'd wait for @mih review, but I think there are no controversial additions being made here, and there is much to do after the brainhack of the last two days. Improvements to this PR are highly welcome as separate PRs or issues.

**Pull request merged**
