### PR TITLE
WIP: Contribution acknowledgements, fixes #140

### LINKED ISSUE #140: Contributor credit?
At the moment the book has a single set of authors. For 3rd-party contributions it might be important to document authorship in a more detailed fashion. Maybe a statement underneath the chapter title would work?

That being said, I would very much prefer to have the whole book being a single editable, evolving entity and not a collection of contributed chapters, where we would have to contact original authors to edit their contributions.

ATM we link the 'contributor list' on the frontpage to https://github.com/datalad-handbook/book/graphs/contributors While this is technically precise, it focuses on the commit of a contribution. But in reality such a contribution could have been the result of debate and evaluation of multiple people.

A dedicated hand-written 'contributors' section could be a solution to both issues: declare original authorship when desired, and acknowledge non-commit contributions.

I have no good idea on how to structure/order such a page. I would like to avoid having to "weigh" contributions in order to determine a subjective importance. The only other two orders I can think of are alphabetical and 'order of appearance' -- and I Iike the latter more.

What do you think?

### PR DESCRIPTION
**Pull request by adswa**
This includes information and contributors, and how to add contributors to our acknowledgments.

### CODE REVIEW

**Comment by mih** [comment]
Is the allcontributors spec open to arbitrary fields? If somehow possible, we could then use it as canonical source and add affiliation and orcid in there too.

**Comment by adswa** [comment]
It looks like one can define templates in the .all-contributorsrc file (https://allcontributors.org/docs/en/bot/configuration). I'll find out!

**Comment by adswa** [comment]
If I understand it correctly, custom types of contributions are possible. But I have asked [here](https://github.com/all-contributors/all-contributors/issues/301) whether any form of "extended" contribution is possible as well. Let's leave this PR open until we know more.

**Comment by adswa** [comment]
Unfortunately, the template cannot take arbitrary keys, and it is out of the scope of the project, according to the maintainers.

**Comment by mih** [comment]
Hmm, I thought this was merged already. Any reason to keep it WIP? We can deal with a script to automate zenodo.json updates later.

**Comment by adswa** [comment]
Oh, no - also forgot about this. Feel free to merge.

**Pull request merged**
