### PR TITLE
Run code examples in a sanitized environment

### PR DESCRIPTION
**Pull request by mih**
- [x] needs autorunrecord 0.4 or later (requirements adjusted)
- [x] rebuild recorded examples (works for me, but better if done
      by someone else too for verification (@adswa)
- [x] adjust `clean-examples` target in `Makefile`, but I am reluctant to say `rm -rf /home/me/*`
      Should we have another directory inside `/home/me`? But it would make all paths longer. However, this is a small price for a future contributor with a `me` useraccount...
- [x] fixes gh-53
- [x] fixes gh-189

In order to not have to run everything in a tmp directory, I decided to
have a proper alternative HOME dir -- this will look more familiar.

This requires manual setup (on each machine that shall build code
examples, i.e. not on readthedocs):

```
sudo mkdir /home/me
sudo chown $USER:$USER /home/me
```

until https://github.com/datalad/datalad/issues/3750 is fixed, it also
requires:

```
HOME=/home/me git config --global user.name "Elena Piscopia"
HOME=/home/me git config --global user.email "elena@example.net"
```

Example diff

```diff
--- a/docs/basics/_examples/DL-101-101-101
+++ b/docs/basics/_examples/DL-101-101-101
@@ -1,6 +1,6 @@
 $ datalad create --description "course on DataLad-101 on my private Laptop" -c text2git DataLad-101
-[INFO] Creating a new annex repo at /home/adina/repos/datalad-handbook/docs/_build/wdirs/dl-101/DataLad-101 
+[INFO] Creating a new annex repo at /home/me/dl-101/DataLad-101 
 [INFO] Running procedure cfg_text2git 
 [INFO] == Command start (output follows) ===== 
 [INFO] == Command exit (modification check follows) ===== 
-create(ok): /home/adina/repos/datalad-handbook/docs/_build/wdirs/dl-101/DataLad-101 (dataset)
+create(ok): /home/me/dl-101/DataLad-101 (dataset)
```

### CODE REVIEW

**Comment by adswa** [comment]
This works for me as well, I've ticked the verification TODO. Thanks much for doing this!

I share your reluctance about ``rm -rf me`` (it seems like a not-completely-implausible username). What about something like ``/home/me/dl``? 

I'll also
- [ ] update ``contributing.rst`` accordingly

**Comment by mih** [comment]
Great! Thanks for trying it out!

> What about something like /home/me/dl

That would not be enough, but maybe:

```
% git grep ':workdir:' | cut -d ':' -f 4- | sort | uniq | cut -d '/' -f 1 | uniq
 dl-101
 studyforrest
 usecases
```

**Comment by adswa** [comment]
> That would not be enough, but maybe:
> 
> ```
> % git grep ':workdir:' | cut -d ':' -f 4- | sort | uniq | cut -d '/' -f 1 | uniq
>  dl-101
>  studyforrest
>  usecases
> ```

I'm not sure I understand what you mean. Do you mean removing those three subdirectories individually in the Makefile (instead of ``/home/me/*``)? If we set ``/home/me/dl`` as what was formerly ``docs/_build/wdirs`` or now the ``autorunrecord_basedir``, during ``make`` those three directories would be created, and ``rm -rf /home/me/dl/*`` would get rid of them -- or do you mean ``/home/me/dl`` is still possibly an existing directory?

**Comment by mih** [comment]
Ah, sorry, misunderstood. My only point was to limit the `rm -rf` to the actual directories that would be created by the examples we have at any point. That minimizes the risk, and is orthogonal to any additional constraints we might want to put on the naming of the workdirs.

Apart from the fact that deleting more directories means more risk, I don't think deleting `dl` is particularly safer than deleting `dl-101`.

**Comment by adswa** [comment]
Ah, got it. Sure, sounds sensible!

**Comment by mih** [comment]
Thx for the write up!

**Comment by mih** [comment]
I have updated the Makefile and am trying to recompute all examples.

**Comment by mih** [comment]
Updates are pushed.
There is one open issue: We are using `ls -l` in some places that
reveals that the effective user ID creating files on the machine is
not the fake one we configured. We should check whether it is important
to list this information. If so, we may need to configure a dedicated
user.

**Comment by mih** [comment]
Good to go from my POV. @adswa please merge when you are happy with it.

**Comment by adswa** [comment]
FTR: unfortunately, this does not yet work on brainbfast (i.e. machine I do not have root access to). My current workaround is to downgrade to ``autorunrecord==0.3``. 

Unrelated FTR: Book examples work fine with ``0.12.0rc5``

**Pull request merged**
