### PR TITLE
typos to check RTD builds

### PR DESCRIPTION
**Pull request by adswa**
I'm checking whether RTD PR builds happen now.

### CODE REVIEW

**Comment by mih** [comment]
Where would these RTD build end up?

**Comment by adswa** [comment]
Seems like right here, as a check under each PR (based on the gif [here](https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html))

**Comment by adswa** [comment]
ha, nice. :)

**Comment by adswa** [comment]
This feature is super cool! thx @yarikoptic!!!

**Comment by mih** [comment]
Really sweet! Should we then disable the PR builds on travis? (just keeping the branch builds)?

**Comment by adswa** [comment]
Intuitively I'd say no, as I suspect that Travis will result in more informative crashes and tracebacks, but let me make a commit fail and see how it looks like.

**Pull request merged**
