### PR TITLE
[ENH] replace issue template with the new "form" format

### PR DESCRIPTION
**Pull request by Remi-Gau**
when merged this closes #766 #767 

I switched default branch on my fork to the rendering of the form can be viewed here:
- https://github.com/Remi-Gau/book/issues/new/choose
- https://github.com/Remi-Gau/book/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D+
- https://github.com/Remi-Gau/book/issues/new?assignees=&labels=&template=feature_request.yml

---

Additional info with potential links to add to add to the doc or contributing. Let me know if it should be added somewhere.

There is a video to introduce the forms on the [github youtube channel](https://www.youtube.com/watch?v=qQE1BUkf2-s).

The official documentation is [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

The json schema to help for the yml files to create the forms is [here](https://json.schemastore.org/github-issue-forms.json)
Its documentation is [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

Note that this github feature is still in beta version.

---

### CODE REVIEW

**Comment by mih** [comment]
Very nice! Thx much!

**Comment by adswa** [comment]
So cool :heart_eyes:

**Comment by adswa** [comment]
hey @all-contributors please add @Remi-Gau for infra

**Comment by Remi-Gau** [comment]
Should I do something similar on the main datalad repo ?

**Comment by adswa** [comment]
I'd say yes! And @mih was also enthusiastic. @yarikoptic @mih, say something now if this effort would be futile in any way ;-)

**Pull request merged**
