### PR TITLE
Restructuring for PDF/HTML compatibility and numbering

### PR DESCRIPTION
**Pull request by adswa**
This PR restructures the table of contents in the HTML and PDF version of the handbook. This is done to reduce the significant mismatches between HTML and PDF version (see https://github.com/datalad-handbook/book/issues/38#issuecomment-574225075 for an overview of problems I have identified), and to create a handbook toctree that is allows easy navigation based on Chapter or usecase numbers.

In particular, this PR:

- adds chapter-level toctrees for Basics chapters. This allows to reference chapters (instead of only sections), but more importantly, it allows to combine the 10 index toctrees for the Basics to a single toctree. With this change, the PDF output has one part for the Basics (instead of 10), and what the HTML refers to as "chapters" is now also a chapter in the PDF.
- adds roman numerals to the chapter headings. This is to introduce a form of numbering of chapters for doclinks to refer to, without causing confusion in the (differently, but arabic) numbered table of contents in the PDF
- numbers sections and subsections within chapters automatically. (I.e, Chapter "Roman numeral"; Section "Arabic numeral", highest section number within a chapter is 6 currently. Example of what would be navigatable: "See Chapter IV, Section 2.3 for more details")
- automatically numbers the use cases (Arabic numerals)
- cherry-picks agreed-upon changes from #353 to improve the general feel of the PDF (remove blank pages, enforce figure positions, DataLad-ish heading and background colors, keep hidden sections hidden also in PDF). I will close #353 in favor of this PR.
- cherry-picks useful commits from #366 (transform usecase intro into a list). I will close #366 in favor of this PR.
- some configurations to the latex preamble in conf.py that give a detailed table of contents in the PDF, and allow for a sidebar navigation that resembles that of the toctree in the HTML

### CODE REVIEW

**Comment by adswa** [comment]
FTR: If this PR is merged, I think the only severe deficiency of the PDF version of the book is that findoutmores are not distinguishable from the main text.

**Comment by adswa** [comment]
Note that for across docs referencing we can insert reference handles at any point in the rst documents. An example is http://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#removing-annexed-content-entirely. With the numbering, we can refer to this paragraph with "Chapter VIII, 2.7.2")

**Comment by adswa** [comment]
@mih, let me know whether you're okay with this PR. There's left-over TODOs (we talked about custom numbering in Latex table of contents, numerals types are still subject to discussion), but if possible, I'd like to have the general restructuring in master soon-ish to sort the new usecases in. :)

**Comment by mih** [comment]
Sure, go ahead. I might come back to this at a later point in time. Thx!

**Pull request merged**
