### PR TITLE
typo fixes for 101

### PR DESCRIPTION
**Pull request by AlexandreHutton**
This PR fixes typos in the 101 pages. Some difficult-to-parse sentences were clarified (e.g. 101-101-create.rst).

### CODE REVIEW

**Comment by adswa** [comment]
Hey, @all-contributors, please add @AlexandreHutton for content!

**Comment by adswa** [comment]
Ah, forgot the bloody bot dislikes commas. @all-contributors please add @AlexandreHutton for content.

**Comment by adswa** [comment]
hey @AlexandreHutton , plesae add your information to the [``zenodo.json``](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) if you want to. I'll archive the recent handbook release with zenodo tomorrow-ish, and I'd be happy to have you in the author list as well.

**Comment by AlexandreHutton** [comment]
Done. Thanks!

**Pull request merged**
