### PR TITLE
Fix inconsistent description of push behavior

### PR DESCRIPTION
**Pull request by AKSoo**
Fix parts that #482 did not address for #481.

### CODE REVIEW

**Review by adswa — APPROVED** [review]
Indeed! Thanks a lot for catching this!

**Comment by adswa** [comment]
hey @all-contributors please add @AKSoo for bug, content

**Comment by adswa** [comment]
@AKSoo Please feel free to add yourself to the [zenodo.json](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file, or leave your preferred name, affiliation, and/or orcid and I'll add you to it. We're building the author list from this file :)

**Comment by AKSoo** [comment]
{
      "affiliation": "Korea Advanced Institute of Science and Technology, Daejeon, Korea",
      "name": "Kim, Sin",
      "orcid": "0000-0003-4652-3758"
    }

**Comment by adswa** [comment]
Thx! Added in 71afdfe

**Pull request merged**
