### PR TITLE
Add DataLad OSF to extensions_pkg.rst

### PR DESCRIPTION
**Pull request by ayrustogaru**
fixes adswa/git-annex-remote-osf#12

### CODE REVIEW

**Comment by adswa** [comment]
hey @all-contributors please add @ayrustogaru for content

**Comment by mih** [comment]
Cool! I was about to ask about such a PR ;-)

@ayrustogaru Do you plan on updating the description now that the initial rush is over?

**Comment by ayrustogaru** [comment]
Yeah, I'll do that😁. Apart from expanding the description, is there anything else I need to do?

**Comment by adswa** [comment]
Could you update it with a short description of what it can do (see e.g. the second sentence in the description of its [zenodo record](https://zenodo.org/record/3900278#.XuxmdKaxUUE) and also point to the [documentation](http://docs.datalad.org/projects/osf/en/latest/)? Thank you, @ayrustogaru!

**Comment by ayrustogaru** [comment]
@adswa, Hey!! I updated the description and linked the extension to the documentation.

**Comment by adswa** [comment]
Fantastic, thanks @ayrustogaru :)

**Comment by adswa** [comment]
@ayrustogaru, I completely forgot to ask you: Could you add yourself to the .zenodo.json file?

**Comment by ayrustogaru** [comment]
@adswa Done😄. PR #537 .

**Pull request merged**
