### PR TITLE
Make readers aware of broken-symlink-and-BIDS-validator-issues

### LINKED ISSUE #560: BIDS validator and datalad. "issue" to mention in the FAQ?
**Is your feature request related to a problem? Please describe.**

Not sure if this a datalad "issue" or a bids-validator one.

TL;DR: Adding something to the FAQ mentioning that a BIDS valid dataset will fail to pass the validator if all its annexed content is dropped.

After a `datalad get` the validator will only count the subjects that have some data with no broken link.

This is not a very intuitive behavior and I think that if I did get confused maybe others will too.

**Additional context**

I had made a valid BIDS dataset a long time ago. Look how beautiful it is.
(no comment on the fact that can't count when it comes to subject number) :smile: 

``` shell
~/BIDS/McGurk/rawdata$ tree -d
.
├── stimuli
├── sub-01
│   ├── anat
│   └── func
├── sub-13
│   ├── anat
│   └── func
├── sub-14
│   ├── anat
│   └── func
├── sub-15
│   ├── anat
│   └── func
├── sub-24
│   ├── anat
│   └── func
├── sub-28
│   └── func
├── sub-32
│   ├── anat
│   └── func
├── sub-41
│   ├── anat
│   └── func
├── sub-48
│   ├── anat
│   └── func
├── sub-61
│   ├── anat
│   └── func
├── sub-66
│   ├── anat
│   └── func
├── sub-69
│   ├── anat
│   └── func
├── sub-73
│   ├── anat
│   └── func
├── sub-74
│   ├── anat
│   └── func
├── sub-82
│   ├── anat
│   └── func
└── sub-98
    ├── anat
    └── func
```

Decided to bring it under version control with datalab to also help with publishing and future work.

So now all the big boys have been annexed.

``` shell
~/BIDS/McGurk/rawdata$ tree sub-01
sub-01
├── anat
│   ├── sub-01_T1w.json
│   └── sub-01_T1w.nii -> ../../.git/annex/objects/XQ/Qq/MD5E-s21627856--617772f8e9e9aa020a216bd7954fd20b.nii/MD5E-s21627856--617772f8e9e9aa020a216bd7954fd20b.nii
└── func
    ├── sub-01_task-contextmcgurk_run-01_bold.nii -> ../../.git/annex/objects/pZ/kF/MD5E-s109756768--8f1660222186a790936717f17898fd9f.nii/MD5E-s109756768--8f1660222186a790936717f17898fd9f.nii
    ├── sub-01_task-contextmcgurk_run-01_events.tsv
    ├── sub-01_task-contextmcgurk_run-02_bold.nii -> ../../.git/annex/objects/j6/wm/MD5E-s109756768--856ed3a5e494e016a59f18be3a7cc738.nii/MD5E-s109756768--856ed3a5e494e016a59f18be3a7cc738.nii
    ├── sub-01_task-contextmcgurk_run-02_events.tsv
```

I have pushed it all to GIN

```shell
:~/BIDS/McGurk/rawdata$ datalad siblings
.: here(+) [git]
.: gin(+) [git@gin.g-node.org:/RemiGau/mc_gurk-raw.git (git)]

~/BIDS/McGurk/rawdata$ datalad status --annex all
183 annex'd files (0.0 B/13.2 GB present/total size)
nothing to save, working tree clean
```

But now if I run the validator I get this ~HORROR~ error.

```shell
~/BIDS/McGurk/rawdata$ bids-validator .
bids-validator@1.5.4

	1: [ERR] Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject. (code: 61 - QUICK_VALIDATION_FAILED)
		..
	Please visit https://neurostars.org/search?q=QUICK_VALIDATION_FAILED for existing conversations about this issue.
```

After recovering from the shock I tried to get some data back.
```shell
~/BIDS/McGurk/rawdata$ datalad get sub-01/anat/sub-01_T1w.nii
get(ok): /home/remi/BIDS/McGurk/rawdata/sub-01/anat/sub-01_T1w.nii (file) [from gin...]
```

And this happens.

```
~/BIDS/McGurk/rawdata$ bids-validator .
bids-validator@1.5.4

This dataset appears to be BIDS compatible.

        Summary:                Available Tasks:        Available Modalities: 
        9 Files, 20.63MB        context Mc Gurk         T1w                   
        1 - Subject                                                           
        1 - Session                                                           
```

Same if I get another `anat`
```
~/BIDS/McGurk/rawdata$ datalad get sub-13/anat
get(ok): /home/remi/BIDS/McGurk/rawdata/sub-13/anat/sub-13_T1w.nii (file) [from gin...]                                       
get(ok): /home/remi/BIDS/McGurk/rawdata/sub-13/anat (directory)
action summary:
  get (ok: 2)
(base) remi@remi-XPS-15-9570:~/BIDS/McGurk/rawdata$ bids-validator .
bids-validator@1.5.4

This dataset appears to be BIDS compatible.

        Summary:                 Available Tasks:        Available Modalities: 
        11 Files, 41.26MB        context Mc Gurk         T1w                   
        2 - Subjects                                                           
        1 - Session                                                            
```

But nothing changes if I get one bold `func` file from another subject.

```
~/BIDS/McGurk/rawdata$ datalad get sub-14/func/sub-14_task-contextmcgurk_run-01_*
get(ok): /home/remi/BIDS/McGurk/rawdata/sub-14/func/sub-14_task-contextmcgurk_run-01_bold.nii (file) [from gin...]            
action summary:
  get (notneeded: 1, ok: 1)
(base) remi@remi-XPS-15-9570:~/BIDS/McGurk/rawdata$ bids-validator .
bids-validator@1.5.4

This dataset appears to be BIDS compatible.

        Summary:                 Available Tasks:        Available Modalities: 
        11 Files, 41.26MB        context Mc Gurk         T1w                   
        2 - Subjects                                                           
        1 - Session                                                            
```

### PR DESCRIPTION
**Pull request by adswa**
Fixes #560 with an explicit FAQ on the BIDS validator and a more general note on troubles with broken symlinks for some tools.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Message to past Rémi: "RTFM or to be more precise just even read the --help section of a command!!"

Turns out that the command line bids validator has a couple of ways to "get around" this issue but I think it would be worth putting them in the datalad handbook.

Let me know if you think that some of this should be added in the sections you created.

---

All the following were done on a valid BIDS dataset that has been dataladed (dataladified? datalified?) but with all annexed files dropped.

### the bad
The following will make the bids-validator scream
```
:~$ bids-validator gin/my_sweet_sweet_bids_data/rawdata/  

1: [ERR] Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject. (code: 61 - QUICK_VALIDATION_FAILED)
```

### the sort of good that doesn't work but tries to help
The following will "work"
```
:~$ bids-validator gin/my_sweet_sweet_bids_data/raw/  --ignoreSymlinks 
```

But you will get the extra message: 

```
2: [ERR] This dataset contains remote files. If you would like to validate with remote files, use the --remoteFiles option. (code: 114 - INCOMPLETE_DATASET)
```

### the uglies

Contrary to the previous message using `--remoteFiles` did not help in any of the combinations I tried.

This fails:
```
:~$ bids-validator gin/my_sweet_sweet_bids_data/raw/  --remoteFiles

1: [ERR] Quick validation failed - the general folder structure does not resemble a BIDS dataset. Have you chosen the right folder (with "sub-*/" subfolders)? Check for structural/naming issues and presence of at least one subject. (code: 61 - QUICK_VALIDATION_FAILED)
```


### the good 

The following actually worked:
```
:~$ bids-validator gin/my_sweet_sweet_bids_data/raw/  --ignoreNiftiHeaders --ignoreSymlinks
```

**Comment by adswa** [comment]
Ha, thanks for following up on this! Maybe also I should have RTFM ;-) That's very useful information. Feel free to add it in, else I'll do it later today after a streak of video calls. Thank you!

**Comment by Remi-Gau** [comment]
Won't have time to do the edits that quickly. :dash: 

I will let you do the honors.

**Comment by adswa** [comment]
*[an overly polite clarification ensues to overcome the inevitable deficiencies of communicating online instead of face-to-face]* 

Didn't mean to rush you. I can also wait, if you want to do it. I wouldn't mind doing it myself, or waiting, so just stop me if you want to take a whack at it :)

**Comment by Remi-Gau** [comment]
> _[an overly polite clarification ensues to overcome the inevitable deficiencies of communicating online instead of face-to-face]_
> 
> Didn't mean to rush you. I can also wait, if you want to do it. I wouldn't mind doing it myself, or waiting, so just stop me if you want to take a whack at it :)

hahaha I did not feel like you were being pushy :smile: 

Just wanted to let you know. And also my 2 hands are so full, I wish I were a Hindu deity to help me make progress on this many fronts. 

So I just wanted to say, I would not be able to make a decent addition very soon.

**Comment by adswa** [comment]
cool, got it :) thx

**Comment by yarikoptic** [comment]
Re the bids validator not informative error message, see https://github.com/bids-standard/bids-validator/issues/792

The problem though is a bit less benign -- bids-validator is used as a initial step in many bids apps.  Some do not have an option yet to skip it (e.g https://github.com/PeerHerholz/BIDSonym/issues/35) . And also it might be .json etc files which are also annexed so ignoring niftis would not be sufficient -- I am getting ORPHANED_SYMLINK on scans.tsv .

Filed: https://github.com/bids-standard/bids-validator/issues/1050

**Comment by adswa** [comment]
Some short PR's have been open for a really long while now. Given no-one complained, I will merge them.

**Pull request merged**
