### PR TITLE
Fix dead link to doc

### LINKED ISSUE #556: dead link to docs?
**What does not work?**
The link in 
http://handbook.datalad.org/en/latest/intro/installation.html
to 
http://docs.datalad.org/en/latest/gettingstarted.html
does not work.

Is this the correct one? 
http://docs.datalad.org/en/stable/

### PR DESCRIPTION
**Pull request by Remi-Gau**
should fix #556

I love the smell of a PR in the morning. :fire: :fire: :fire:

### CODE REVIEW

**Comment by adswa** [comment]
hey @all-contributors please add @Remi-Gau for bug

**Comment by adswa** [comment]
Also, please feel free to add yourself to the [.zenodo.json](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file, @Remi-Gau :)

**Comment by Remi-Gau** [comment]
Will do. 

Any order as to where I should add my name in that json file?

**Comment by adswa** [comment]
Mostly people add themselves as second-to-last, i.e., just above Michael. :)

**Comment by Remi-Gau** [comment]
> Mostly people add themselves as second-to-last, i.e., just above Michael. :)

Want to add sentence in the "how to contribute section" while I am at it?

**Comment by adswa** [comment]
> Want me to add a sentence in the "how to contribute section" while I am at it? smile

That would be superb!! thanks so much!

**Comment by Remi-Gau** [comment]
Another thing :

Zenodo allows you to have one DOI for all versions. 

>Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.3608611. This DOI represents all versions, and will always resolve to the latest one. Read more. 

Do you want me to update the page on the readme so it points to this?

**Pull request merged**
