### PR TITLE
Generic command output normalization

### PR DESCRIPTION
**Pull request by mih**
- Set a fixed identity and timestamp for Git (author and committer)
- Set a fixed seed for datalad UUID generation
- Remove all trailing spaces in captured output (avoids pertubations due to different Git configs across contributors)
- Replace virtual env location with 'VIRTUALENV' placeholder
- timestamp normalization in command output
- annex UUID standardization
- `ls -l` output normalization

Related: https://github.com/datalad/datalad/issues/7234

Outputs where captured with `sudo rm -rf /home/me/dl-101 /home/me/basics /home/me/pushes/ ; rm -f docs/basics/_examples/DL-101* ; make build`

### CODE REVIEW

**Comment by adswa** [comment]
This seems to work nicely . I'm thinking about adding the generated code snippets directly to this PR (the full build can complete over lunch) - what do you think?

**Comment by adswa** [comment]
uhh I messed one up that's now missing. Need to push this in a short while (currently running a different build)

**Comment by mih** [comment]
I pushed, what I believe could be the full change for basics 101

**Comment by adswa** [comment]
Thank you!

**Comment by adswa** [comment]
Oh man, I realized a problem this causes. This seems to normalize all dataset UUIDs? I spent hours trying to pinpoint why a create-sibling-ria call would fail, but then I saw that all datasets have identical UUIDs.

**Comment by mih** [comment]
Ah! Good point. That is probably a sideeffect of fixing the random seed for datalad.

I think I will change this to support ENV overrides per `runrecord`, so we can fix the seed whenever needed and only then.

**Comment by mih** [comment]
This is done now. A PR against the handbook is pending.

**Pull request merged**
