### PR TITLE
[ENH] add sphinx-copybutton extension

### LINKED ISSUE #75: improve the way code is displayed
Quickly making a note of https://github.com/datalad-handbook/book/pull/73#discussion_r304781439 to remind us of a JS based solution about visually distinguishing comments and code @mih mentioned in the above command.

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #75 

based on https://github.com/datalad-handbook/book/issues/75#issuecomment-730474769, this PR (through the build artifacts) will allow us to practically inspect how using "sphinx-copybutton" may work.

### CODE REVIEW

**Comment by sappelhoff** [comment]
For example, copying this cell (screenshot of [this](https://datalad-handbook--615.org.readthedocs.build/en/615/basics/101-105-install.html#dataset-archeology)):

image

gives me:

```bash
cd ../../
cat << EOT >> notes.txt
datalad save -m "Add note on datalad clone"
```

... all lines prefixed with `$ ` are found, stripped of that prefix, and returned

But copying this cell (screenshot of [that](https://datalad-handbook--615.org.readthedocs.build/en/615/intro/installation.html#initial-configuration)):

image


gives me the whole cell, because no `$` prefix was found:

```bash
# enter your home directory using the ~ shortcut
% cd ~
% git config --global --add user.name "Bob McBobFace"
% git config --global --add user.email bob@example.com
```


--- 

we could also use a regex to configure more than one prefix we want to "detect". I think this works very nicely :-) WDYT?

**Review by adswa — APPROVED** [review]
Ha, nice! Thanks for the addition, @sappelhoff. I tried it out locally, and it works very well for single lines of code with a ``$`` prefix.

I've toyed around with the regex for a bit locally, trying to make here docs or multi-line commands work, but so far I've failed with one edge-case-problem after the other ;-) I'm happy to at least make the single line case work much easier with this addition.
Could you please make a small note mentioning the copy-button in [docs/intro/narrative.rst](https://github.com/datalad-handbook/book/blob/master/docs/intro/narrative.rst) about copy-pasting code?
And also please feel free to add yourself to the zenodo.json file :)

**Comment by adswa** [comment]
hey @all-contributors please add @sappelhoff for infra, tool

**Comment by sappelhoff** [comment]
> Could you please make a small note mentioning the copy-button in docs/intro/narrative.rst about copy-pasting code?

:+1: 

I tried to use the [⎘](https://www.compart.com/de/unicode/U+2398) icon in the intro as an approximation of the "copybutton" ... it'd be best perhaps to use the actual copybutton [icon](https://github.com/executablebooks/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copy-button.svg), but it may also be overkill.

Do you have a link to the examples that currently don't work?

**Comment by adswa** [comment]
> Do you have a link to the examples that currently don't work?

Anything that is a multi-line command, split with ``\`` such as 

```
   $ datalad download-url http://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-Guide.pdf \
     --dataset . \
     -m "add beginners guide on bash" \
     -O books/bash_guide.pdf
```
in the end of [the second section](https://github.com/datalad-handbook/book/blob/master/docs/basics/101-102-populate.rst), or any of the ``here documents`` (the first one is in the [third section](https://github.com/datalad-handbook/book/blob/master/docs/basics/101-103-modify.rst)) where the text that gets re-directed into a file is not prefixed with a ``$``

```
$ cat << EOT > notes.txt
   One can create a new dataset with 'datalad create [--description] PATH'.
   The dataset is created empty

   EOT
```

FTR: I've opened a feature request to copy-button: https://github.com/executablebooks/sphinx-copybutton/issues/105.

**Comment by sappelhoff** [comment]
I see, I didn't know what a "here document" was until now :-) 

thanks for opening the feature request!

**Comment by adswa** [comment]
Its ancient, but super convenient to write formatted text into a file from the terminal :-) I'd say we wait for a response on the feature request until proceeding. I'll cherry-pick 6d8cabc into master, later, though, just to have you in zenodo.json when we make the next release.

**Comment by sappelhoff** [comment]
> I'd say we wait for a response on the feature request until proceeding.

agreed, it'd be great to support these two types of code snippets as well.

Thanks for the cherry-picking. Good thing I made a separate commit for that ;-)

**Comment by sappelhoff** [comment]
> FTR: I've opened a feature request to copy-button: executablebooks/sphinx-copybutton#105.

Unfortunately we didn't get much input so far, but I took some time and prepared a PR that may suffice for our needs: https://github.com/executablebooks/sphinx-copybutton/pull/126

**Review by sappelhoff — COMMENTED** [review]
Hi @adswa I added the requirement to sphinx-copybutton and my PR just got merged. I now updated this PR, and I think the line-continuation and here-document cells now work like we want them to work.

I'd appreciate a review! Below two links to test the copybutton in the RTD build artifact:

- example for line continuation from this page: https://datalad-handbook--615.org.readthedocs.build/en/615/basics/101-102-populate.html

- example for here-document from this page: https://datalad-handbook--615.org.readthedocs.build/en/615/basics/101-103-modify.html

**Comment by adswa** [comment]
This is fantastic @sappelhoff , thank you so much for your efforts! I apologize in advance for a delay, a number of deadlines loom over me. It looks good on first sight, an I hope I can get to try it out and comment more within this week :)

**Comment by adswa** [comment]
This is so cool! :heart: Apologies for getting to this with such a delay :( Again one of these things that would have been done in 5 minutes had I just not pushed it at the end of my todo-list ... :facepalm: 

@mih, @yarikoptic check this out! It works flawlessly!

**Comment by sappelhoff** [comment]
No worries, thanks for maintaining this book! I am happy to see this in :-)

**Pull request merged**
