### PR TITLE
Update dgpa.rst

### PR DESCRIPTION
**Pull request by eltociear**
Github -> GitHub

### CODE REVIEW

**Review by adswa — APPROVED** [review]
Hey, thanks for your patience and sorry about the silence - I was on vacation :)  thanks for the fix!

**Comment by adswa** [comment]
@all-contributors please add @eltociear for bug

**Comment by adswa** [comment]
Feel free to add yourself to the [Zenodo.json](https://github.com/datalad-handbook/book/blob/master/.zenodo.json) file in this repository with a new PR. This is where we generate the books author list from.

**Comment by eltociear** [comment]
@adswa Thanks!
opened new PR.
https://github.com/datalad-handbook/book/pull/829

**Pull request merged**
