### PR TITLE
Final tune-ups prior to the release

### PR DESCRIPTION
**Pull request by adswa**
- [x] complete acknowledgements
- [x] chapter numbering
- [ ] front page note on version
- [x] completely new example output generated with latest release candidate
- [ ] Fix-up too nested findoutmores (see #495)
- [ ] Update public datasets

### CODE REVIEW

**Comment by mih** [comment]
I will push an update to `funding.svg` soonish.

**Comment by mih** [comment]
Updated funding figure is now in https://github.com/datalad-handbook/artwork/commit/a0a6f4b59080dcf9fe70e31da39259167846ecbb

**Comment by adswa** [comment]
Thx, I have pushed a submodule update

**Comment by adswa** [comment]
hey @DorienHuijser, I forgot to ask you to add you to .zenodo.json and took the liberty to do this - hope thats okay :)

**Comment by DorienHuijser** [comment]
Wow, you're giving me way too much credit here!!

**Pull request merged**
