### PR TITLE
Update .zenodo.json

### PR DESCRIPTION
**Pull request by marisaheckner**

### CODE REVIEW

**Comment by adswa** [comment]
Thx! Do you have an ORCID ID you want to add as well?

**Comment by marisaheckner** [comment]
Not yet, does it make sense to register?
Btw nicely written abstract. I'm struggling with mine atm...

**Comment by adswa** [comment]
Yes, its very useful to have an ORCID! I'd recommend it (and the library here requires it actually). Its fast, checkout [orcid.org](https://orcid.org/). And its good to have your ORCID here, because once well release the books next version (soon), that will be directly credited to you.

**Comment by marisaheckner** [comment]
Oh I apparently signed up before ;-) I added it, thanks!

**Comment by adswa** [comment]
awesome, thx!

**Pull request merged**
